### ISSUE TITLE
Add functions to determine relationship of terms in hierarchy to each other

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/OLPG#14]
given term t1 and t2 determine if

1. t1 is a subclass or superclass of t2
2. t1 and t2 are siblings (have the same direct parent)
3. t1 and t2 are not siblings but have a common ancestor that is not the root
4. t1 and t2 have only the root as common ancestor

The functions should allow one to specify the root term, which can be either the root of the entire ontology or an other arbitrary term.

The classification results should be returned as an enumeration constant

These functions will be useful for the annotation merging (MONDO) and other algorithms.

**Comment by julesjacobsen** [comment]
These look like they should be static methods like Math.max(i1, i2) you don't need an enumeration constant if a simple boolean will suffice.
```java
class Graph {
    //Depending on how Term is implemented, this might make more sense on Term than Graph
    static boolean isSubClass(t1, t2);

    static boolean areSiblings(t1, t2);

    static boolean areRelated(t1, t2);

    static boolean areUnrelated(t1, t2);
}
```

**Comment by pnrobinson** [comment]
Hi Jules,
these are suggestions for the interface rather than references to existing code, right?
We are thinking about using a general graph library, so I am not sure it makes sense to code this say in the current DirectedGraph class. 
I was thinking about an enumeration constant because I was thinking of a switch statement in the downstream algorithm, but this is not a major point.
I would say that for now I would add functions like this to the class OntologyAlgorithm -- this will make it easier to switch the graph implementation later on. I would also pass the ontology object and the intended root, but I agree these should be static functions.

**Comment by pnrobinson** [comment]
Here are my suggested implementations, 
```
public static boolean isSubclass(Ontology ontology, TermId source, TermId dest) {
    return ontology.getAncestorTermIds(source).contains(dest);
  }
```
and
```
public static boolean termsAreSiblings(Ontology ontology, TermId t1, TermId t2)  {
    Set<TermId> parents1 = getParentTerms(ontology,t1,false); // false=do not include t1 itself
    Set<TermId> parents2 = getParentTerms(ontology,t2,false); // ditto
    parents1.retainAll(parents2); // transforms parents1 into the intersection of parents1 and parents2
    return (! parents1.isEmpty());
  }
```
and
```
public static boolean termsAreRelated(Ontology ontology,TermId t1, TermId t2) {
    Set<TermId> ancs1 = ontology.getAncestorTermIds(t1);
    Set<TermId> ancs2 = ontology.getAncestorTermIds(t2);
    ancs1.retainAll(ancs2);
    for (TermId tid : ancs1) {
      if (! ontology.isRootTerm(tid)) { return true; }
    }
    return false;
  }
```
and finally
```

  public static boolean termsAreUnrelated(Ontology ontology,TermId t1, TermId t2) {
    return (! termsAreRelated(ontology,t1,t2));
  }
```

**Comment by cmungall** [comment]
For ontologies like GO, Uberon you would want to include other relationship types.

**Comment by pnrobinson** [comment]
@cmungall currently, I think the graph algorithms are not worrying about the edge types, and so the code would not work for GO etc if relations other than is_a are used. I do not think we can address this issue now until we decide on a new Graph library. I think it would be good to support at least GO in any case

**Comment by pnrobinson** [comment]
I am checking in some code -- a few changes from the above were necessary. The code lives in
the class ``OntologyAlgorithm`` and there is a new test class called ``OntologyAlgorithmTermRelationTest``

New code with immutable library:
```
 public static boolean termsAreSiblings(Ontology ontology, TermId t1, TermId t2)  {
    Set<TermId> parents1 = getParentTerms(ontology,t1,false); // false=do not include t1 itself
    Set<TermId> parents2 = getParentTerms(ontology,t2,false); // ditto
    return (!Sets.intersection(parents1,parents2).isEmpty());
  }
```

**Comment by pnrobinson** [comment]
I am going to merge this code into the master version 1.1.4 if there is no objection. We need this for HpoAnnotQc and LP2PG

**Comment by pnrobinson** [comment]
closing, have added new functions and test class
