### ISSUE TITLE
Maven enforcer

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/OLPG#25]
There are several difficult maven enforcer problems that made a maven build impossible. That is, the libraries included now in OLPG refer to different versions of other libraries, e.g., apache-commons-io 2.2 and 2.4 (and many more). I think this means that OLPG is fine from within an IDE but did not build with maven. I have tried to get rid of the issues by specifying the most recent libraries in the top level pom file and trying to exclude older version of the libraries from other dependencies that were using them but did not get things to work.
For now, I commented out the enforcer plugin, which is bad form, but to get other code to work this weekend. We need to iron this out soon

**Comment by pnrobinson** [comment]
@yy20716 Thanks for the code in the change-common-to-generic branch -- that compiles fine on my machine. For some reason the merge did not overwrite the pom.xml file in master but I am unable to perform a PR on it, maybe I have done something dumb? I am confused now with the branching structure, not sure we are using the same branching strategy -- I do not care which but we should agree (we have often used master-develop-feature branch with occasional hotfix to master & develop). 
Can you take a look please? thanks ! Peter

**Comment by yy20716** [comment]
Thank you for letting me know. 
 - I will try to follow the branching strategy as you suggested. 
 - Yes, so it seems that obographs and OLPG use different versions of libraries so I initially tried to specify the most recent versions but then obographs does not work. In the end, I had to add some exclusion statements in ontolib-io/pom.xml. I am also not sure why the OLPG's master pom.xml is not pushed but let me quickly make a pull request for the updated pom.xml. Thank you.

**Comment by pnrobinson** [comment]
Thanks, this is now resolved!
