### ISSUE TITLE
GoAnnotationFile Version 2.1

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/OLPG#5]
Currently experiencing file parsing errors for goa_human.gaf version 2.1 in the GoGeneAnnotationParser.

<img width="957" alt="goa_human gaf" src="https://user-images.githubusercontent.com/7397665/35881144-e0dd4884-0b4d-11e8-9196-52b204452241.png">

After reviewing the file there was two comment lines (maybe unintentional by GO).

<img width="436" alt="go_fault" src="https://user-images.githubusercontent.com/7397665/35883297-c6ad702c-0b54-11e8-9c85-3153675e226c.png">

I reviewed the ontolib-io code and it seems to assume that comments will only exist that the beginning of the file. I will open a PR with a quick fix.

**Comment by pnrobinson** [comment]
I am closing this, as this is working now.
